export let mainarray = [
    {image: 'images/products/athletic-cotton-socks-6-pairs.jpg',
     content: 'black-and-grey-authentic-cotton-socks-6-pairs',
     rating: {stars: 4.5, counts: 87},
     pricecents: 1090},
    {image: 'images/products/intermediate-composite-basketball.jpg',
     content: 'Intermediate-Size-Basketball',
     rating: {stars: 4.5, counts: 87},
     pricecents: 1090},
    {image: 'images/products/adults-plain-cotton-tshirt-2-pack-teal.jpg',
     content: 'Adults-Plain-Cotton-T-Shirt-2-Pack',
     rating: {stars: 4.5, counts: 56},
     pricecents: 1090},
    {image: 'images/products/6-piece-non-stick-baking-set.webp',
     content: '6-piece-non-stick-baking-set',
     rating: {stars: 4.5, counts: 175},
     pricecents: 3499},
    {image: 'images/products/6-piece-white-dinner-plate-set.jpg',
     content: '6-piece-white-dinner-plate-set',
     rating: {stars: 4, counts: 37},
     pricecents: 2067},
    {image: 'images/products/backpack.jpg',
     content: 'black-backpack-safari',
     rating: {stars: 4.5, counts: 80},
     pricecents: 4121},
    {image: 'images/products/men-athletic-shoes-green.jpg',
     content: 'mens-shoes-brown-adidas',
     rating: {stars: 4, counts: 229},
     pricecents: 3890},
    {image: 'images/products/electric-glass-and-steel-hot-water-kettle.webp',
     content: 'electric-glass-and-steel-hot-water-kettle',
     rating: {stars: 5, counts: 846},
     pricecents: 3074},
    {image: 'images/products/straw-sunhat.webp',
     content: 'straw-sunhat',
     rating: {stars: 4, counts: 215},
     pricecents: 2200},
    {image: 'images/products/non-stick-cooking-set-15-pieces.webp',
     content: 'non-stick-cookware',
     rating: {stars: 4.5, counts: 511},
     pricecents: 6797},
    {image: 'images/products/women-knit-ballet-flat-black.jpg',
     content: 'women-knit-ballet-flat-black',
     rating: {stars: 4, counts: 326},
     pricecents: 2640},
    {image: 'images/products/round-sunglasses-black.jpg',
     content: 'mens-sunglasses-black',
     rating: {stars: 4.5, counts: 30},
     pricecents: 1560}
];
